//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class amphibia
    {
        public long IdAmphibia { get; set; }
        public long IdEspecie { get; set; }
        public string Sinonimia { get; set; }
        public string Identificacion { get; set; }
        public string Descripcion { get; set; }
        public string ColorEnVida { get; set; }
        public string Diagnosis { get; set; }
        public string Morfometria { get; set; }
        public string SVLMacho { get; set; }
        public string ReferenciaSVLMacho { get; set; }
        public string SVLHembra { get; set; }
        public string ReferenciaSVLHembra { get; set; }
        public string Comportamiento { get; set; }
        public string Larva { get; set; }
        public string Canto { get; set; }
        public string ColorEnPreservacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    
        public virtual especie especie { get; set; }
    }
}
