//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ave
    {
        public long IdAves { get; set; }
        public long IdEspecie { get; set; }
        public string Identificacion { get; set; }
        public bool CasiEndemica { get; set; }
        public string TaxonomiaRidgelyGreenfield { get; set; }
        public string ComentarioTaxonomia { get; set; }
        public string Movimiento { get; set; }
        public string DistribucionSubespecies { get; set; }
        public string NotaPresenciaProvincia { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    
        public virtual especie especie { get; set; }
    }
}
