//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalogo
    {
        public catalogo()
        {
            this.especiecatalogoes = new HashSet<especiecatalogo>();
            this.ImagenEspecimen = new HashSet<ImagenEspeciman>();
            this.multimedias = new HashSet<multimedia>();
            this.nombrecomuncatalogoes = new HashSet<nombrecomuncatalogo>();
            this.publicacioncatalogoes = new HashSet<publicacioncatalogo>();
            this.publicacionenlaces = new HashSet<publicacionenlace>();
            this.reptiliacatalogoes = new HashSet<reptiliacatalogo>();
        }
    
        public long IdCatalogo { get; set; }
        public string Nombre { get; set; }
        public string Sigla { get; set; }
        public string Descripcion { get; set; }
        public long IdTipoCatalogo { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    
        public virtual tipocatalogo tipocatalogo { get; set; }
        public virtual ICollection<especiecatalogo> especiecatalogoes { get; set; }
        public virtual ICollection<ImagenEspeciman> ImagenEspecimen { get; set; }
        public virtual ICollection<multimedia> multimedias { get; set; }
        public virtual ICollection<nombrecomuncatalogo> nombrecomuncatalogoes { get; set; }
        public virtual ICollection<publicacioncatalogo> publicacioncatalogoes { get; set; }
        public virtual ICollection<publicacionenlace> publicacionenlaces { get; set; }
        public virtual ICollection<reptiliacatalogo> reptiliacatalogoes { get; set; }
    }
}
