//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class divisiongeopoliticacatalogoap
    {
        public int IdDivisionGeopoliticaCatalogoAP { get; set; }
        public long IdDivisionGeopolitica { get; set; }
        public long IdCatalogo { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    }
}
