//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenEspeciman
    {
        public long IdImagenEspecimen { get; set; }
        public string Titulo { get; set; }
        public string NombreArchivo { get; set; }
        public Nullable<long> IdEspecimen { get; set; }
        public string Descripcion { get; set; }
        public Nullable<long> IdCatalogo { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    
        public virtual catalogo catalogo { get; set; }
        public virtual especiman especiman { get; set; }
    }
}
