//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class multimedia
    {
        public long IdMultimedia { get; set; }
        public string Titulo { get; set; }
        public string NombreArchivo { get; set; }
        public long IdTaxa { get; set; }
        public Nullable<long> IdTipo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Principal { get; set; }
        public bool Descarga { get; set; }
        public long IdCatalogo { get; set; }
        public bool EnlaceExterno { get; set; }
        public Nullable<bool> Borrado { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string FuenteBibliografica { get; set; }
        public string Duracion_ms { get; set; }
        public string FrecuenciaInicial_KHz { get; set; }
        public string FrecuenciaMaxima_KHz { get; set; }
        public string FrecuenciaFinal_KHz { get; set; }
        public string FrecuenciaMinima_KHz { get; set; }
        public string FrecuenciaPuntoInflexion_KHz { get; set; }
        public string FrecuenciaMaximaEnergia_KHz { get; set; }
        public string AnchoBanda_KHz { get; set; }
        public string Software { get; set; }
        public string Grabadora { get; set; }
        public string Detector { get; set; }
        public string SituacionGrabacion { get; set; }
        public string Responsable { get; set; }
        public string DuracionMinima { get; set; }
        public string DuracionMaxima { get; set; }
        public string FrecuenciaInicialMinima { get; set; }
        public string FrecuenciaInicialMaxima { get; set; }
        public string FrecuenciaMaximaMinima { get; set; }
        public string FrecuenciaMaximaMaxima { get; set; }
        public string FrecuenciaFinalMinima { get; set; }
        public string FrecuenciaFinalMaxima { get; set; }
        public string FrecuenciaMinimaMinima { get; set; }
        public string FrecuenciaMinimaMaxima { get; set; }
        public string FrecuenciaPuntoInflexionMinima { get; set; }
        public string FrecuenciaPuntoInflexionMaxima { get; set; }
        public string FrecuenciaCaracteristica { get; set; }
        public string FrecuenciaCaracteristicaMinima { get; set; }
        public string FrecuenciaCaracteristicaMaxima { get; set; }
        public string FrecuenciaMaximaEnergiaMinima { get; set; }
        public string FrecuenciaMaximaEnergiaMaxima { get; set; }
        public string AnchoBandaMinima { get; set; }
        public string AnchoBandaMaxima { get; set; }
    
        public virtual catalogo catalogo { get; set; }
        public virtual taxa taxa { get; set; }
        public virtual tipo tipo { get; set; }
    }
}
