//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class nombrecomunpublicacion
    {
        public long idnombrecomunpublicacion { get; set; }
        public long idnombrecomun { get; set; }
        public long idpublicacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    
        public virtual nombrecomun nombrecomun { get; set; }
        public virtual publicacion publicacion { get; set; }
    }
}
