//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class nombrecomun
    {
        public nombrecomun()
        {
            this.nombrecomuncatalogoes = new HashSet<nombrecomuncatalogo>();
            this.nombrecomunpublicacions = new HashSet<nombrecomunpublicacion>();
        }
    
        public long IdNombreComun { get; set; }
        public long IdTaxa { get; set; }
        public string Nombre { get; set; }
        public string Comentario { get; set; }
        public bool Principal { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<long> IdPublicacion { get; set; }
        public Nullable<bool> Borrado { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    
        public virtual publicacion publicacion { get; set; }
        public virtual taxa taxa { get; set; }
        public virtual ICollection<nombrecomuncatalogo> nombrecomuncatalogoes { get; set; }
        public virtual ICollection<nombrecomunpublicacion> nombrecomunpublicacions { get; set; }
    }
}
