//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISOSPERFIL
    {
        public long IDPERMISOSPERFIL { get; set; }
        public long IDPERFIL { get; set; }
        public long IDMENU { get; set; }
        public Nullable<bool> SELECCIONARPERFIL { get; set; }
        public Nullable<bool> INSERTARPERFIL { get; set; }
        public Nullable<bool> ACTUALIZARPERFIL { get; set; }
        public Nullable<bool> ELIMINARPERFIL { get; set; }
        public Nullable<System.DateTime> FECHAMODIFICACION { get; set; }
        public string USUARIOMODIFICACION { get; set; }
    
        public virtual MENU MENU { get; set; }
        public virtual PERFIL PERFIL { get; set; }
    }
}
