//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class publicacionano_bak
    {
        public long IdPublicacionAno { get; set; }
        public long Ano { get; set; }
        public long IdPublicacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    }
}
