//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class publicacionautor
    {
        public long IdPublicacionAutor { get; set; }
        public long IdPublicacion { get; set; }
        public long IdAutor { get; set; }
        public int OrdenAutor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    
        public virtual autor autor { get; set; }
        public virtual publicacion publicacion { get; set; }
    }
}
