//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class publicacion
    {
        public publicacion()
        {
            this.especimen = new HashSet<especiman>();
            this.nombrecomuns = new HashSet<nombrecomun>();
            this.nombrecomunpublicacions = new HashSet<nombrecomunpublicacion>();
            this.publicacionautors = new HashSet<publicacionautor>();
            this.publicacioncatalogoes = new HashSet<publicacioncatalogo>();
            this.publicacionenlaces = new HashSet<publicacionenlace>();
            this.sinonimoes = new HashSet<sinonimo>();
            this.taxapublicacions = new HashSet<taxapublicacion>();
        }
    
        public long IdPublicacion { get; set; }
        public string Titulo { get; set; }
        public string TituloSecundario { get; set; }
        public bool Editor { get; set; }
        public string Editorial { get; set; }
        public string Volumen { get; set; }
        public string Numero { get; set; }
        public string Pagina { get; set; }
        public string PalabrasClave { get; set; }
        public string Resumen { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaCreacionRegistro { get; set; }
        public bool PublicacionDelQcaz { get; set; }
        public bool PublicaEnNoticias { get; set; }
        public bool PublicaEnWeb { get; set; }
        public bool PublicaEnCV { get; set; }
        public Nullable<int> IdExterno { get; set; }
        public string FuenteIdExterno { get; set; }
        public string Publisher { get; set; }
        public string PubLocalidad { get; set; }
        public string Cita { get; set; }
        public string CitaCorta { get; set; }
        public Nullable<bool> Borrado { get; set; }
        public Nullable<int> Ano { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    
        public virtual ICollection<especiman> especimen { get; set; }
        public virtual ICollection<nombrecomun> nombrecomuns { get; set; }
        public virtual ICollection<nombrecomunpublicacion> nombrecomunpublicacions { get; set; }
        public virtual ICollection<publicacionautor> publicacionautors { get; set; }
        public virtual ICollection<publicacioncatalogo> publicacioncatalogoes { get; set; }
        public virtual ICollection<publicacionenlace> publicacionenlaces { get; set; }
        public virtual ICollection<sinonimo> sinonimoes { get; set; }
        public virtual ICollection<taxapublicacion> taxapublicacions { get; set; }
    }
}
