//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class publicacionenlace
    {
        public long IdPublicacionEnlace { get; set; }
        public string NombreArchivo { get; set; }
        public string EnlaceArchivo { get; set; }
        public string TextoEnlace { get; set; }
        public long IdPublicacion { get; set; }
        public long IdCatalogo { get; set; }
        public bool Descarga { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    
        public virtual catalogo catalogo { get; set; }
        public virtual publicacion publicacion { get; set; }
    }
}
