//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxaaudio
    {
        public long IdTaxaAudio { get; set; }
        public long IdTaxa { get; set; }
        public long IdAudio { get; set; }
        public long IdCatalogo { get; set; }
        public byte PublicaEnWeb { get; set; }
        public Nullable<byte> OrdenPresentacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    }
}
