//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipocatalogo
    {
        public tipocatalogo()
        {
            this.catalogoes = new HashSet<catalogo>();
            this.tipocatalogo1 = new HashSet<tipocatalogo>();
        }
    
        public long IdTipoCatalogo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<long> IdTipoCatalogoPadre { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    
        public virtual ICollection<catalogo> catalogoes { get; set; }
        public virtual ICollection<tipocatalogo> tipocatalogo1 { get; set; }
        public virtual tipocatalogo tipocatalogo2 { get; set; }
    }
}
