//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public long IDUSUARIO { get; set; }
        public Nullable<long> IDPERFIL { get; set; }
        public string USERUSUARIO { get; set; }
        public string PASSWORDUSUARIO { get; set; }
        public string RETRYPASSWORDUSUARIO { get; set; }
        public string NOMBREUSUARIO { get; set; }
        public string APELLIDOUSUARIO { get; set; }
        public string DIRECCIONUSUARIO { get; set; }
        public string TELEFONOUSUARIO { get; set; }
        public string EMAILUSUARIO { get; set; }
        public Nullable<System.DateTime> FECHAMODIFICACION { get; set; }
        public string USUARIOMODIFICACION { get; set; }
    
        public virtual PERFIL PERFIL { get; set; }
    }
}
