//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class verificacionlocalidad
    {
        public long IdVerificacionLocalidad { get; set; }
        public long IdLocalidad { get; set; }
        public long IdPersonal { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Observacion { get; set; }
        public string Fuente { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    }
}
